CRR - Friendship v1 - Social Media APP
kevcap/ror-social-scaffold pull request #2
Opened 2020-09-07 19:07 UTC by kevincappuccino

## This project was implemented with the following features:
- [x] Associations (has_many, belongs_to)
- [x] Friendship request (send, receive, accept, reject)
- [x] Invite users at user list or single page user.
- [x] Tests with capybara and rspec
- [x] CSS validation with rubocop
### Plus: 
✨Like counter
✨Logged username

2020-09-07 20:49 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for the well done job so far
However, there are some issues to have to be solved

1. It's asked, read it [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png), the posts timeline must include posts written by logged-in user and their friends. It's not implemented like this in your webapp

2. It's required that, read it it[here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png), there should be a button to invite user to friendship on users list page and on single user page. In your application it only appears on the Users list page not on Single page. Add it, please.

3. REad the comments below.

4. Add integration tests for **friendship request**

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-09-07 20:49 UTC, maelfosso commented on app/views/users/show.html.erb
> +        <% end %>
Please, logic are not allowed in views. Implement it into views helpers

2020-09-07 20:49 UTC, maelfosso commented on app/views/users/index.html.erb
> +        <% end %>
Remove the logic from views, please. Implement them in views helpers

2020-09-09 12:54 UTC, kevincappuccino commented
# Hey @maelfosso 👋 I tried to talk with you through slack to check that points below, but I didn't get any answer 😕.

## Summing up I'm afraid that there are some issues on that review, please check down below:
"It's required that, read it there, there should be a button to invite user to friendship on users list page and on single user page. In your application, it only appears on the Users list page not on Single page. Add it, please."

### However I already have that feature as you can see below.
![image](https://user-images.githubusercontent.com/56762529/92600233-a91a5680-f281-11ea-94de-6220a1392d0a.png)
### About the friendship test, I added it as a unit test just as the requirement says.  It doesn't have to be an integrated spec test. I also have integrated tests, btw.
![image](https://user-images.githubusercontent.com/56762529/92600268-b59eaf00-f281-11ea-95c0-ab3bae49de83.png)

Regards!

2020-09-09 13:06 UTC, rOluochKe approved these changes
Hello @kevincappuccino 
### You did well :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-09-14 12:57 UTC, merged